import { useState } from 'react';
import { analyzeSentiment } from './heuristic';

export default function App() {
  const [text, setText] = useState('');
  const result = text.trim() ? analyzeSentiment(text) : null;

  const sentimentColor = result?.sentiment === 'positive' ? 'text-green-400' :
    result?.sentiment === 'negative' ? 'text-red-400' : 'text-neutral-400';

  return (
    <div className="min-h-dvh bg-neutral-950 text-neutral-100 flex flex-col">
      <header className="flex items-center gap-3 px-4 py-3 border-b border-neutral-800">
        <a href="https://freerobotstore.online" className="text-neutral-500 hover:text-neutral-300 text-sm">
          FreeRobotStore
        </a>
        <h1 className="font-semibold text-lg" style={{ fontFamily: 'var(--font-serif)' }}>
          Sentiment Analyzer
        </h1>
        <span className="ml-auto text-xs px-2 py-0.5 rounded bg-neutral-800 text-neutral-400">
          Heuristic — no model needed
        </span>
      </header>

      <main className="flex-1 flex flex-col max-w-2xl mx-auto w-full p-4 gap-4">
        <textarea
          value={text}
          onChange={(e) => setText(e.target.value)}
          placeholder="Type or paste text to analyze sentiment..."
          className="w-full h-40 p-4 rounded-lg bg-neutral-900 border border-neutral-800 resize-none focus:outline-none focus:border-neutral-600 text-neutral-100 placeholder:text-neutral-600"
        />

        {result && (
          <div className="bg-neutral-900 border border-neutral-800 rounded-lg p-4 space-y-3">
            <div className="flex items-center gap-4">
              <span className={`text-2xl font-bold ${sentimentColor}`}>
                {result.sentiment === 'positive' ? '+' : result.sentiment === 'negative' ? '-' : '~'}
                {' '}{result.sentiment.charAt(0).toUpperCase() + result.sentiment.slice(1)}
              </span>
            </div>
            <div className="grid grid-cols-2 gap-4 text-sm">
              <div>
                <span className="text-neutral-500">Score</span>
                <span className={`ml-2 font-mono ${sentimentColor}`}>{result.score}</span>
                <span className="text-neutral-600 ml-1">(-1 to +1)</span>
              </div>
              <div>
                <span className="text-neutral-500">Confidence</span>
                <span className="ml-2 font-mono text-neutral-300">{(result.confidence * 100).toFixed(0)}%</span>
              </div>
            </div>
          </div>
        )}

        <p className="text-xs text-neutral-600">
          This agent uses heuristic code — no AI model, no download, instant results.
          The analysis code was generated by an LLM and evolved through iterative testing.
        </p>
      </main>

      <footer className="text-center text-xs text-neutral-600 py-3 border-t border-neutral-800">
        Heuristic agent — zero model, zero inference, zero cost.
        <a href="https://github.com/FreeRobotStore/platform/blob/main/agents/sentiment/web/src/heuristic.ts" className="underline ml-1">View source</a>
      </footer>
    </div>
  );
}
